name: CI/CD for Azure CDC Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run tests (if any)
      run: poetry run pytest || echo "No tests found"

    - name: Build Docker image
      run: docker build -t azure-cdc .

    - name: Login to Azure Container Registry
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image to ACR
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        docker tag azure-cdc ${{ secrets.ACR_LOGIN_SERVER }}/azure-cdc:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/azure-cdc:latest